cart/urls.py
from django.urls import path

from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name="cart_add"),
    path('delete/', views.cart_delete, name="cart_delete"),
    path('update/', views.cart_update, name="cart_update"), 
    path('orderplaced/', views.order_placed, name='order_placed'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('orders/', include('orders.urls', namespace='orders')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

cart/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
# Create your models here.

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta: 
        verbose_name_plural = 'Categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])
    

    def __str__(self):
        return self.name 


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator')
    name = models.CharField(max_length=255)
    quantity = models.IntegerField(default=10)
    size = models.CharField(max_length=3)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta: 
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])
    
    def __str__(self):
        return self.name 

cart/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from store.models import Product
from .cart import Cart

def cart_summary(request):
    cart = Cart(request)
    return render(request, 'store/cart/summary.html', {'cart': cart})

def cart_add(request):
    cart = Cart(request)        
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        cart.add(product=product, qty=product_qty)
        cart_qty = cart.__len__()
        response = JsonResponse({'qty':cart_qty})
        return response

def cart_delete(request):
        cart = Cart(request)
        if request.POST.get('action') == 'post':
            product_id = int(request.POST.get('productid'))
            cart.delete(product=product_id)

            cartqty = cart.__len__()
            carttotal = cart.get_total_price()
            response = JsonResponse({'qty': cartqty, 'subtotal': carttotal})
            return response

def cart_update(request):
        cart = Cart(request)
        if request.POST.get('action') == 'post':
            product_id = int(request.POST.get('productid'))
            product_qty = int(request.POST.get('productqty'))
            cart.update(product=product_id, qty=product_qty)

            cartqty = cart.__len__()
            carttotal = cart.get_total_price()
            response = JsonResponse({'qty': cartqty, 'subtotal': carttotal})
            return response

def order_placed(request):
    cart = Cart(request)
    return render(request, 'payment/orderplaced.html')

store/views.py
from django.shortcuts import get_object_or_404, render
from .models import Category, Product

def categories(request):
    return {
        'categories': Category.objects.all()
    }

def product_all(request):
    products = Product.products.all()
    return render(request, 'store/home.html', {'products': products})

def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/detail.html', {'product': product})

def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.products.filter(category=category)  
    return render(request, 'store/products/category.html', {'category': category, 'products': products})

templates/store/cart/summary.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Cart Summary{% endblock %}
{% block content %}

<main class="pt-5">
  <div class="container">
    <h1 class="h5">Shopping cart</h1>
    {% for item in cart %}
    {% with product=item.product %}
    <div data-index="{{product.id}}" class="row mb-4 border product-item">
      <div class="col-md-3 col-lg-2 order-md-first bg-light">
        <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image" src="{{ product.image.url }}">
      </div>
      <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
        <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset">
          <h1 class="h5 pt-2">{{ product.name }}</h1>
        </a>
        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
                <div class="col-6">Pret</div> 
              <div class="col-6 text-end"><span class="h6 fw-bold">{{ item.product.price }} RON</span></div>
            </div>
          </div>
          <div class="col">
            <div class="row p-3">
              <div class="col-12">
                <label for="select">Quantity</label>
                <select id="select{{product.id}}">
                  <option selected>
                    {{item.qty}}
                  </option>
                  <option value="">1</option>
                  <option value="">2</option>
                  <option value="">3</option>
                  <option value="">4</option>
                  <option value="">5</option>
                </select>
                <button type="button" id="update-button" data-index="{{product.id}}"
                  class="btn btn-outline-secondary btn-sm update-button">
                  Update
                </button>
                <button type="button" id="delete-button"  data-index="{{product.id}}"
                  class="btn btn-outline-secondary btn-sm delete-button">
                  Delete
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endwith %}
    {% endfor %}
    <div class="col-12 text-end">
      <div class="h6 fw-bold">Sub Total: <div id="subtotal" class="d-inline-flex">{{cart.get_total_price}} RON</div></div>
      <div> <a href="{%url "cart:order_placed" %}" class="btn btn-primary my-2">Checkout</a> </div>
    </div>
  </div>
</main>
<script>
  // Delete Item
  $(document).on('click', '.delete-button', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "cart:cart_delete" %}',
      data: {
        productid: $(this).data('index'),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        $('.product-item[data-index="' + prodid + '"]').remove();
        document.getElementById("subtotal").innerHTML = json.subtotal;
        document.getElementById("cart-qty").innerHTML = json.qty
      },
      error: function (xhr, errmsg, err) {}
    });
  })

  // Update Item
  $(document).on('click', '.update-button', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "cart:cart_update" %}',
      data: {
        productid: $(this).data('index'),
        productqty: $('#select' + prodid + ' option:selected').text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        document.getElementById("cart-qty").innerHTML = json.qty
        document.getElementById("subtotal").innerHTML = json.subtotal
      },
      error: function (xhr, errmsg, err) {}
    });
  }) 
</script>

{% endblock %}